Cyberwatch/cyberwatch_api_toolbox

.gitignore, README.md, cbw_api_toolbox/__init__.py, cbw_api_toolbox/__routes__.py, cbw_api_toolbox/cbw_api.py, cbw_api_toolbox/cbw_auth.py, cbw_api_toolbox/cbw_objects/cbw_application.py, cbw_api_toolbox/cbw_objects/cbw_cve.py, cbw_api_toolbox/cbw_objects/cbw_group.py, cbw_api_toolbox/cbw_objects/cbw_package.py, cbw_api_toolbox/cbw_objects/cbw_server.py, cbw_api_toolbox/cbw_parser.py, examples/count_computer_by_group.py, examples/servers_applications_export.py, examples/servers_by_group.py, requirements.txt, setup.py
- Ajout des classes de base au sein d'un module installable via pip
- Ajout de 2 examples correspondants au issue support #102 et #51
=> Add CBW auth class and server group scripts

README.md, cbw_api_toolbox/__routes__.py, cbw_api_toolbox/cbw_api.py
- Improve README
- Add ping route
=> Add ping route

cbw_api_toolbox/cbw_api.py, cbw_api_toolbox/cbw_auth.py, cbw_api_toolbox/cbw_objects/cbw_application.py, cbw_api_toolbox/cbw_objects/cbw_cve.py, cbw_api_toolbox/cbw_objects/cbw_group.py, cbw_api_toolbox/cbw_objects/cbw_package.py, cbw_api_toolbox/cbw_objects/cbw_server.py, cbw_api_toolbox/cbw_parser.py, examples/count_computer_by_group.py, examples/servers_applications_export.py, examples/servers_by_group.py
Ensure python3.5 compatibility
=> Ensure python3.5 compatibility

cbw_api_toolbox/cbw_api.py
Related to https://github.com/Cyberwatch/cyberwatch_api_toolbox/issues/3
=> API_URL errors catching

README.md
Enhances the README.md by using more readable markdown syntax, and changing the ways sections are separated to be more visual-friendly.
Also adds a table of contents
=> enhance README.md

cbw_api_toolbox/__routes__.py, cbw_api_toolbox/cbw_api.py
Signed-off-by: Robin BECHON <robin@cyberwatch.fr>
=> refactoring requesting methods

.travis.yml, cbw_api_toolbox/cbw_parser.py, tox.ini
Fix some useless changes on logging messages
Add tox to travis_ci and renaming testenv
=> follow-up add_test_ci

spec/test_cbw_api.py
Add comment to help creating new vcr cassettes
=> Add comment on how to use vcrpy

spec/fixtures/vcr_cassettes/get_detailed_servers.yaml, spec/fixtures/vcr_cassettes/server_failed.yaml, spec/fixtures/vcr_cassettes/server_ok.yaml, spec/fixtures/vcr_cassettes/servers_ok.yaml, spec/test_cbw_api.py
Add test for methods server, servers and get_detailed_servers
Signed-off-by: Robin BECHON <robin@cyberwatch.fr>
=> Add sucess tests for method server/servers/get_detailed_servers

cbw_api_toolbox/__routes__.py, cbw_api_toolbox/cbw_api.py
It is now possible to do POST request with request method
=> Api refacto

cbw_api_toolbox/cbw_api.py, examples/delete_server.py, spec/fixtures/vcr_cassettes/delete_server_with_server_id.yaml, spec/fixtures/vcr_cassettes/delete_server_without_server_id.yaml, spec/test_cbw_api.py
Add the method verif_response to simplify the code.
Add the delete_server method to delete a server.
Add example file for the delete_server method.
Create unit tests for the delete_server method.
=> Add method delete_server

cbw_api_toolbox/cbw_api.py, examples/update_server_groups.py, spec/fixtures/vcr_cassettes/update_server.yaml, spec/fixtures/vcr_cassettes/update_server_with_group_none.yaml, spec/test_cbw_api.py
add the add_group_server method with the unit tests that come with it and the test file.
=> Add method add_groups_server

cbw_api_toolbox/__routes__.py, cbw_api_toolbox/cbw_api.py, cbw_api_toolbox/cbw_objects/cbw_node.py, cbw_api_toolbox/cbw_objects/cbw_remote_access.py, examples/remote_accesses.py, spec/fixtures/vcr_cassettes/remote_accesses.yaml, spec/test_cbw_api.py
Add routes remotes_accesses
Add method remote_accesses
=> Remote accesses

cbw_api_toolbox/cbw_api.py, examples/create_remote_access.py, spec/fixtures/vcr_cassettes/create_remote_access.yaml, spec/fixtures/vcr_cassettes/create_remote_access_failed_without_address.yaml, spec/test_cbw_api.py
add method create_remote_access
=> Create remote access

examples/remote_accesses.py
Add comment for file examples/remote_accesses
=> Add comment for file examples/remote_accesses

cbw_api_toolbox/cbw_api.py, examples/remote_access.py, spec/fixtures/vcr_cassettes/remote_access.yaml, spec/fixtures/vcr_cassettes/remote_access_wrong_id.yaml, spec/test_cbw_api.py
add method remote_access
add test for method remote_access
=> Remote access

cbw_api_toolbox/cbw_api.py, examples/delete_remote_access.py, spec/fixtures/vcr_cassettes/delete_remote_access.yaml, spec/fixtures/vcr_cassettes/delete_remote_access_wrong_id.yaml, spec/test_cbw_api.py
Add method delete_remote_access
=> Add method delete_remote_access

cbw_api_toolbox/cbw_api.py, examples/update_remote_access.py, spec/fixtures/vcr_cassettes/update_remote_access.yaml, spec/fixtures/vcr_cassettes/update_remote_access_without_type.yaml, spec/test_cbw_api.py
add a method update_remote_access
=> Update remote access

cbw_api_toolbox/__init__.py, cbw_api_toolbox/cbw_api.py, examples/delete_server.py, examples/servers_by_group.py
add CBWLogger in file CBWApi.py
add basic config in __init__.py
=> add CBWLogger

README.md, cbw_api_toolbox/cbw_api.py, examples/ping.py
=> Update method ping

cbw_api_toolbox/cbw_file_xlsx.py, cbw_api_toolbox/cbw_objects/cbw_server.py, examples/export_remote_acces_file_xls.py, spec/fixtures/vcr_cassettes/export_file_xlsx.yaml, spec/test_cbw_files_xlsx.py, tox.ini
=> Add method (export_xls)

examples/view_server_patch.py
script that displays the details of a server #40
=> script that displays the details of a server

cbw_api_toolbox/cbw_api.py, examples/update_server_groups.py
update method for criticality, etc #39
=> enhance serverupdate

cbw_api_toolbox/cbw_api.py
update method (update_remote_access) for receive all parameter
=> Enhance remote acess update

cbw_api_toolbox/cbw_objects/cbw_deploying_period.py, cbw_api_toolbox/cbw_objects/cbw_ignoring_policy.py, cbw_api_toolbox/cbw_objects/cbw_ignoring_policy_items.py, cbw_api_toolbox/cbw_objects/cbw_server.py, examples/server.py
add attributes for CBWServer (deploying, etc)
=> Add attributes for CBWserver (deploying, etc)

documentation.md
Documentation api
1ere partie
-definition des méthodes et exemples d'usage
-Objet serveur avec ses attributs documentes 
=> documentation api

README.md
I add a link to the documentation in the readme.
fixes #49
=> link to documentation

cbw_api_toolbox/cbw_objects/cbw_server.py, documentation.md
Added field created_at and relevant documentation (also some small documentation changes)
Wait for the API changes to occur before merging (https://gitlab.cbw.io/CyberwatchTeam/OLYMPE/merge_requests/3656)
=> add created_at field and fix some documentation

examples/cleanup_initialization_duplicates.py
Example of a cleanup script that can clean :
- hostname in duplicates
- agents in initialization for more than 3 months (default value)
- agentless connections in initialization for more than 6 months (default value)
=> Add example cleanup script

.gitignore, api.conf, examples/server_to_splunk.py
- Added example for splunk upload
- Added config file `api.conf` for future refactoring
=> add splunk script example and config file

cbw_api_toolbox/__routes__.py, cbw_api_toolbox/cbw_api.py, documentation.md, examples/cve_announcement.py
fix #59 
Allow users to query the API to get the informations about a CVE from the toolbox.
=> added support for cve_announcements#show

cbw_api_toolbox/cbw_file_xlsx.py
=> Ignore E1133 non-iterable value for server.groups

.pylintrc, cbw_api_toolbox/cbw_file_xlsx.py
=> Disable not-an-iterable

spec/fixtures/vcr_cassettes/cve_announcement.yaml, spec/fixtures/vcr_cassettes/cve_announcement_failed.yaml, spec/test_cbw_api.py
Issue #60 
Added unit tests for cve_announcements
=> add unit test for Cve_announcements

cbw_api_toolbox/cbw_api.py, documentation.md, examples/ram_test_deploys.py, spec/fixtures/vcr_cassettes/test_deploy.yaml, spec/fixtures/vcr_cassettes/test_deploy_failed.yaml, spec/test_cbw_api.py
Issue #66 
- Added new method "test_deploy_remote_access" 
- Added example script using test_deploy_remote_access
- Unit tests for the feature
=> Tests deploys by api

requirements.txt, setup.py
Issue #78 
Add missing packages in requirements.txt
=> added missing_requirements in requirements.txt

cbw_api_toolbox/cbw_objects/cbw_ignoring_policy.py, cbw_api_toolbox/cbw_objects/cbw_server.py, cbw_api_toolbox/cbw_objects/cbw_users.py, examples/servers_by_group.py
Issue #83 
- Refactored models so that arrays [] returns an empty array and not None if empty
- Cleaned an example of useless checks thanks to the refactoring
=> Refactor models

examples/affect_group_os.py
Issue #64 
Added example script to affect groups depending on the OS of the server
=> example script to affect groups by OS

documentation.md
Issue #97
Added remote access object/attributes to documentation.md
=> Added object/attributes remote access

documentation.md
Added missing example for method `users`  + fix a typo
=> added missing user method example + typo

documentation.md
Issue #99 
Modified some headers in documentation.md to be able to use Markdown links
=> Fix duplicate headers

cbw_api_toolbox/cbw_objects/cbw_users.py, documentation.md
Closes #102 
Added `auth_provider` to User object and updated documentation
=> Updated User object + documentation

examples/affect_group_by_hostname.py
=> add example script to affect groups based on hostname

cbw_api_toolbox/cbw_objects/cbw_server.py, documentation.md
Added CVSS metrics to CVE model
=> Added CVSS metrics

cbw_api_toolbox/__routes__.py, cbw_api_toolbox/cbw_api.py, documentation.md, spec/fixtures/vcr_cassettes/ping_ok.yaml, spec/fixtures/vcr_cassettes/ping_without_api_key.yaml, spec/fixtures/vcr_cassettes/ping_without_secret_key.yaml
=> Migrate route ping to v3

examples/remote_access_create.py, examples/remote_access_update.py
Changed some `mandatory` parameters to `optional` in some examples
=> Changed some requirements in examples

examples/servers_detail_export_xlsx.py
Added an `export vulnerabilities to XLSX` example script
=> Added detailed servers export example

cbw_api_toolbox/__routes__.py, cbw_api_toolbox/cbw_api.py, cbw_api_toolbox/cbw_objects/cbw_node.py, documentation.md, examples/nodes.py, spec/fixtures/vcr_cassettes/delete_node.yaml, spec/fixtures/vcr_cassettes/node.yaml, spec/fixtures/vcr_cassettes/nodes.yaml, spec/test_cbw_api.py
- Added route `nodes` from api v3
- Added method `nodes`, `node`, `delete_node`
- Updated unit tests
=> Added route nodes from api v3

cbw_api_toolbox/__routes__.py, cbw_api_toolbox/cbw_api.py, cbw_api_toolbox/cbw_objects/cbw_host.py, documentation.md, examples/create_host.py, examples/hosts.py, spec/fixtures/vcr_cassettes/create_host.yaml, spec/fixtures/vcr_cassettes/delete_host.yaml, spec/fixtures/vcr_cassettes/host.yaml, spec/fixtures/vcr_cassettes/hosts.yaml, spec/fixtures/vcr_cassettes/update_host.yaml, spec/test_cbw_api.py
- Added `hosts` route from  api v3
- Update documentation
- Unit tests
=> Added route Hosts from api v3

cbw_api_toolbox/cbw_api.py, spec/fixtures/vcr_cassettes/nodes.yaml, spec/test_cbw_api.py
Added pagination to `users` and `nodes`
=> added pagination to nodes and users

README.md
Add a section in README to link the new Documentation
=> New documentation section

cbw_api_toolbox/__routes__.py, cbw_api_toolbox/cbw_api.py, cbw_api_toolbox/cbw_objects/cbw_group.py, documentation.md, examples/group_create.py, spec/fixtures/vcr_cassettes/create_group.yaml, spec/fixtures/vcr_cassettes/delete_group.yaml, spec/fixtures/vcr_cassettes/group.yaml, spec/fixtures/vcr_cassettes/update_group.yaml, spec/test_cbw_api.py
- Migrated `groups` to api v3
- Added more unit tests
=> Update route Groups to v3

cbw_api_toolbox/cbw_api.py, examples/update_server_cve.py, spec/fixtures/vcr_cassettes/update_server_cve.yaml, spec/fixtures/vcr_cassettes/update_server_cve_ignored.yaml, spec/test_cbw_api.py
- Add methode update_server_cve
- Update units tests
=> Add method update_server_cve

cbw_api_toolbox/cbw_api.py, cbw_api_toolbox/cbw_objects/cbw_server.py, examples/delete_cve_announcement.py, spec/fixtures/vcr_cassettes/delete_cve_announcement.yaml, spec/test_cbw_api.py
#128 
- Added route `delete_cve_announcement`
=> Added delete_cve_announcement route

cbw_api_toolbox/cbw_objects/cbw_server.py, documentation.md, examples/cleanup_initialization_duplicates.py
Removed `agent_version` from model and script since it's no longer returned by the API
=> Remove agent_version

.pylintrc, cbw_api_toolbox/cbw_api.py, examples/update_cve_announcement.py, spec/fixtures/vcr_cassettes/update_cve_announcement.yaml, spec/test_cbw_api.py
#128 
- Added `CVSS custom` and `score custom`
- Added `update_cve_announcement` route
=> added cvss custom + update_cve route

examples/generate_html_and_pdf_reports_patches_for_network_exploitable_vulns.py
This script lets the user generate a PDF / HTML report on the patches you should apply to remove a set of filtered CVEs.
=> Add script to export patches on filtered cves

examples/added_date.py
Script to describe all computers in the database with their creation date and the creation hour.
=> Pull request nicolas

setup.py
=> Bump to 1.1.1

examples/create_remote_by_host.py
Add script to find unsupervised hosts and create an agentless connection for them
=> Linux ram creation from hosts example

cbw_api_toolbox/cbw_objects/cbw_server.py, documentation.md, examples/server_update.py
#133 
Updated server object to use environment object instead of criticality
=> Change Criticality to Env object

cbw_api_toolbox/cbw_api.py, examples/importer/upload_importer_results.py
Issue #150 
To be merged after #149 
- Add route to upload Importer scanning scripts results
- Example for uploading scanning script results
=> Add route to upload Importer scanning scripts results

examples/importer/download_importer_scripts.py
Remove a folder cleanup in download_importer_scripts.py
=> Remove a folder cleanup in download_importer_scripts.py

cbw_api_toolbox/cbw_api.py
=> writing api method to launch script on a server

cbw_api_toolbox/cbw_api.py
=> Implementing "server_schedule_update" method

cbw_api_toolbox/cbw_objects/cbw_security_issue.py, documentation.md
Updating 'Security Issue' model to parse CVE codes correctly
=> Updating 'Security Issue' model

examples/view_dashboard_indicator.py
=> print cve announcements and assets informations

examples/view_dashboard_indicator.py
Updating server_outdated_system() according to API changes, server_reboot_required() and  print_results()
=> Updating on methods (cve_lists, server_reboot_required, print_results)

example_api.conf, examples/server_to_qradar.py
Issue #108 
Example QRadar integration with HTTP Receiver with JSON format for payload
=> Example for QRadar integration with HTTP Receiver

examples/server_affect_ignoring_policy.py
Add script to affect ignoring policy to all servers
=> Add affect Ignoring Policy script

examples/server_affect_ignoring_policy.py
Fix typo + changing `ignoring_policy_id` to `ignoring_policy`
=> Fix ignoring policy script

examples/server_to_qradar.py
Improved example for QRadar integration with HTTP Receiver
=> Improved example for QRadar integration with HTTP Receiver

examples/cve_published_last_month_export_xlsx.py
Example script to export CVE published last month in an XLSX file.
=> add example to export cve published last month

examples/email_report.py, examples/servers_detail_export_xlsx.py
=> "exploitable" replace by "exploit code maturity"

example_api.conf
short addition to example_api.conf that is used in some scripts
=> add smtp to example_api.conf

examples/cve_published_last_month_export_xlsx.py
Update the script to follow API changes
=> update cve_published_last_month_export_xlsx.py to match API changes

.example_pypirc, .gitignore, CONTRIBUTING.md, README.md, setup.py
Add a new process to install cuberwatch_api_toolbox with `pip`
Documentation on how to push a new version to PyPi
=> Add new pip install/update process

examples/create_remote_by_host.py
Fix Pylint error for `raise` exception
=> Fix pylint error from new pylint version

examples/importer/download_importer_scripts.py
Fix error when using importer script in localhost environment
=> Fix importer script when running in local/self-signed environment

setup.py
=> Bump version to 2.0.1 for release

examples/detail_servers.py
=> CSV file for fixes and CVE informations by asset

documentation.md
Updated objects with prioritized_cve_announcements/prioritized notion
Updated documentation
=> Updated objects with prioritized_cve_announcements/prioritized

examples/cve_announcements_filter.py
Add example on route cve_announcements with a filter
Clean up cve model object
=> add example filter on cve announcement + clean up

documentation.md
Update CveAnnouncement object documentation
=> Update CveAnnouncement object documentation

examples/servers_detail_export_xlsx.py
#142 
*  Refactored and cleaned `servers_details_export_xlsx.py`
=> Refactored + clean servers_details_export_xlsx.py

cbw_api_toolbox/cbw_api.py
#200 
Update "create_remote_access" route to enable the use of credentials id
=> Update "create_remote_access" route to enable the use of credentials id

examples/affect_repository_to_group.py
Add script to affect a custom repository to servers in a specific group
=> Add script to affect a repository to a server group

examples/create_multiple_remote_accesses.py
Add example to create agentless connection with a credential ID + groups
=> Add example to create agentless connection with a credential ID + groups

setup.py
=> Bump to 2.0.3

examples/host_detail_export_xlsx.py
=> Export host to xslsx

examples/cleanup_duplicates_communication_failure.py
Add script to delete duplicates with communination failure
=> Add script to delete duplicates with communination failure

examples/find_outdated_last_detection.py
Add script to find servers with  a CVE 'last detection' higher than 40 days
=> Add script to find servers with outdated 'last detection'

examples/create_multiple_remote_accesses.py
Added more features to `create_multiple_remote_accesses.py`
=> Added more features to an example script

README.md, setup.py
Updated API documentation links
=> Updated API documentation links

cbw_api_toolbox/cbw_api.py
Add route to update compliance assets
=> Add route to update compliance assets

cbw_api_toolbox/cbw_api.py
=> fix error messages in API

setup.py
=> Bump to 2.0.4

cli/docker_image/__init__.py, cli/docker_image/create.py, cli/docker_image/list_images.py, cli/docker_image/scan.py, cli/docker_image/show.py, cli/docker_image/update.py, cli/docker_image/utils.py, requirements.txt, tox.ini
This PR adds the two new folders `bin` and `cli` to the static_analysis tox job. It also fix all the errors reported by pylint in these two folders.
Closes #237
=> Add static_analysis verification to bin and cli folders

.github/workflows/main.yml, .gitleaks.toml
This PR adds a github action to check if secrets have been commited. It adds a specific configuration file `.gitleaks.toml` that excludes credentials from `examples/` and `spec/`.
Closes #196
=> Add gitleaks github action

examples/cleanup_lost_com_filters.py
Add example to cleanup lost_communication servers with filter
=> Add example to cleanup lost_communication servers with filter

examples/email_report_filters.py
Add example of email report with filters
=> Add example of email report with filters

cli/airgap/download_compliance_scripts.py
Updated 'groups' to 'repositories' for compliance cli for 10.6
=> Updated 'groups' to 'repositories' for compliance cli

setup.py
=> Bump to 2.2.2

README.md
Close #261 
Fix a link issue in ToC
=> Fix README toc

cbw_api_toolbox/cbw_api.py, setup.py
Add server_reboot route + version bump
=> Add server_reboot route + version bump

cbw_api_toolbox/cbw_api.py
Previously, only the first page was fetched.
Closes #273
=> Fetch all OS by looping over pages

cbw_api_toolbox/cbw_api.py, setup.py
=> Fix status code 2xx

cbw_api_toolbox/cbw_api.py
=> add proxy support

cbw_api_toolbox/cbw_api.py, setup.py
Changed return code to 201 for upload airgap route
=> Fix return code for upload airgap
