- cbw_api_toolbox/cbw_objects/cbw_cve.py
- cbw_api_toolbox/cbw_objects/cbw_group.py
- cbw_api_toolbox/cbw_objects/cbw_node.py
- cbw_api_toolbox/cbw_objects/cbw_package.py
- cbw_api_toolbox/cbw_objects/cbw_remote_access.py
- cbw_api_toolbox/cbw_objects/cbw_server.py
There was an error when the cyberwatch api had more fields than the cyberwatch_api_tools object.
> Fix cbw_objects with **kwargs

- cbw_api_toolbox/cbw_objects/cbw_server.py
- documentation.md
Issue #81 
Using the new attribute `score` instead of `cve_score` for CVSS v3 score compatibility
> Replacing cve_score with score

- cbw_api_toolbox/cbw_objects/cbw_group.py
- documentation.md
The PowerShell API has a `description` attribute  for the object `groups` that was missing in the Python API group model
- Added `description`  attribute to `group` model
> Added description attribute to group model

- documentation.md
The API does not return that much information about the node object yet.
> Update documentation.md Node

- cbw_api_toolbox/cbw_api.py
The method cve_announcements() requires a mandatory parameter that should actually be optional
> Make params optional for cve_announcements

- cbw_api_toolbox/cbw_api.py
- If not specified, 100 objects will be returned by default
- Page param is now handled by `_get_pages` instead of individual code block for each method
> refactored  pagination handling

- cbw_api_toolbox/cbw_objects/cbw_server.py
A list of CVE objects was not suitable for the cve_announcements attribute for the server model. The API indeed returns server_cve attributes. 
The cve_code was the only common attribute. With this change we now can access the fixed_at, comment, and ignored property of a server_cve when we query the api for a server.
This change is breaking and will impact existing scripts.
> GET on specifi servers now returns a list of server_cve dictionnaries and no longer cve objects

- setup.py
Version 1.1.2 : in cbw_server.py, self.cve_announcements is assigned directly to the object affected at initialization instead of a parsed object.
> updating library version

- examples/create_remote_by_host.py
When raising a new exception (rather than using a bare raise to re-raise the exception currently being handled), the implicit exception context can be supplemented with an explicit cause by using from with raise:
raise new_exc from original_exc
The expression following from must be an exception or None. It will be set as __cause__ on the raised exception. Setting __cause__ also implicitly sets the __suppress_context__ attribute to True, so that using raise new_exc from None effectively replaces the old exception with the new one for display purposes (e.g. converting KeyError to AttributeError), while leaving the old exception available in __context__ for introspection when debugging.
[See documentation for more](https://docs.python.org/3/library/exceptions.html)
Signed-off-by: Nicolas …
> Fixing the re-raising bug

- cbw_api_toolbox/cbw_api.py
Allow the use of CBW_API_URL, CBW_API_KEY and CBW_SECRET_KEY environnement variables to interact with the API.
Closes #227
> Allow environnement variables in CBWApi

- bin/cyberwatch-cli
- cli/__init__.py
- cli/docker_image/__init__.py
- cli/docker_image/create.py
- cli/docker_image/list.py
- cli/docker_image/scan.py
- cli/docker_image/show.py
- cli/docker_image/update.py
- setup.py
This MR adds the `show vulnerabilities` subcommand for docker-images proposed in issue #233. This is still a work-in-progress.
The following commands are added:
The list command truncates image name to 30 characters.
```sh
$ cyberwatch-cli docker-image list
ID  IMAGE:TAG                      NODE SERVER ENGINE REGISTRY
1   library/a_very_too_long_name_w 1    431    2      1       
2   library/ubuntu:latest          1    432    2      1       
3   library/ubuntu:18.04           1    433    2      1       
4   library/node:12                1    434    2      1       
```
```sh
$ export DOCKER_IMAGE_ID=3
$ cyberwatch-cli docker-image show vulnerabilities $DOCKER_IMAGE_ID
CVE            SCORE TECHNOLOGIES
CVE-2020-3810  5.5   debian:apt,debian:debian_linux
CVE-2020-27350 5.7 …
```
> Add `show vulnerabilities` subcommand for docker-images

- docs/cli.md
This MR document the `list` and `show vulnerabiliies`  subcommands of the `docker-image` resource.
> doc(cli): add 'list' and 'show vulns' docker-image subcommands

- .dockerignore
- Dockerfile
- docs/cli.md
This PR adds a `Dockerfile` that can be used to run the `cyberwatch-cli` program easily inside a docker container.
> Add a Dockerfile to run the cli

- .gitleaks.toml
The pipeline https://github.com/Cyberwatch/cyberwatch_api_toolbox/runs/2120731255 failed because all `=` in commits were matched by the base64 regexp. This PR modifies the regexp to match exactly API keys.
> Fix gitleaks by matching exactly api credentials

- bin/cyberwatch-cli
- cbw_api_toolbox/cbw_api.py
- cli/airgap/__init__.py
- cli/airgap/download_scripts.py
- cli/airgap/upload.py
- docs/cli.md
This PR adds the `airgap_script` resource to the command line interface. It adds `download` and `upload` subcommand.
The workflow is:
1. Download the scripts (the default destination is `Scripts`).
```sh
cyberwatch-cli airgap download-scripts --dest-dir /tmp/scripts
cyberwatch-cli airgap download-scripts
```
2. Run the scripts.
```sh
mkdir assets
/tmp/script/Linux/run > "assets/$(hostname)"
```
3. Upload the results.
```sh
cyberwatch-cli airgap upload assets/*
```
Closes #228
> Add `download` and `upload` subcommands to `airgap_script`

- bin/cyberwatch-cli
It is important to exit with a code different from 0 so that CI/CD pipelines
detect that something is wrong and fail.
There was also missing an `f` to enable the f-string.
> Exit with code 1 when resource is wrong

- bin/cyberwatch-cli
When the resource was `docker-image`, the else statement was executed. This is
not the indented behaviour.
> Fix wrong if-if-else logic

- cbw_api_toolbox/cbw_api.py
With the previous version, url terminated by a slash was not supported. This
version relies on python's `urllib.parse.joinurl` function that is more resilient.
However, `urljoin` can only join 2 arguments. Moreover, it has a strange
behavior:
```python
>>> urljoin("https://localhost/api/v2/assets", "1")
https://localhost/api/v2/1
```
As the last element in the first URL does not end with a `/`, it is overridden.
To avoid these problems, urljoin is wrapped in a `reduce` function and a `/` is appended to each `base_url` element.
> Strengthen route builder

- requirements.txt
- setup.py
This fixes an error with the docker container that reported a missing `chardet` module.
> Add Chardet module to requirements

- cbw_api_toolbox/cbw_api.py
Use the logger and exit instead of raising an exception.
> Improve missing api variable error

- examples/cleanup_duplicates.py
The "server_update_comm_fail" status is not longer supported by our API.
That is why we delete the communication failure test for each tested server.
> The "server_update_comm_fail" status is not longer supported on /servers

- README.md
This method has been shown to be deprecated.
A new paragraph links to the new method
> added deprecated + new api method

- .github/workflows/release.yml
The 'release' workflow was running on ubuntu-18.04 which wasn't supported anymore since 03/04/2023 ([https://github.com/actions/runner-images/issues/6002](https://github.com/actions/runner-images/issues/6002)).
Now it is always using the 'ubuntu-latest' image, as stated in the documentation : [https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
> Update the 'release' workflow 
